### ISSUE TITLE
Hardware & Eagle files = 404

### ISSUE THREAD

**Issue by zanthor** [RCDaddy/T-Box#8]
I'm new to this so maybe I'm doing something wrong, but right now if I click on the links I get 404's.

**Comment by RCDaddy** [comment]
Yea sorry about that. The Main page is half finished. Will be finished in the next few hours. However, you can find the eagle files the in src/ directory.

I'll update this ticket as soon as it's done.

**Comment by RCDaddy** [comment]
Ok, updated readme.md correcting the link.

**Comment by zanthor** [comment]
OK, I'm apparently an idiot because I can't figure out how to add another
issue...  I'm a total GIT newb so I apologize...

I had a set of the v1.0 rev 4 boards made at OSHPark, and I ordered an
arduino pro mini to solder onto it, the 6 pins at the end do not line up,
and I'm not sure if this is intentional and I'm missing something or an
error.. and I can't seem to find the "add new issue" button I found earlier.

**Comment by RCDaddy** [comment]
It's ok, i'm new to this too!

There are roughly 4-5 variations on the pro mini, each one with the pins laid out slightly differently. The main row of pins should fit perfectly but the others can be worked around by using single core wire.

This is the main reason why i created v1.1.

**Comment by zanthor** [comment]
yay! Gotta love standards... the rest of the pins do line up perfectly, and
I happen to have a nice collection of cable which will work nicely to
bridge that gap.
